### ISSUE TITLE
create zorin os/zorin os lite guide

### ISSUE THREAD

**Issue by electron271alt** [theandor/discord-ccbot#26]
Hey i'm electron271s alt and would really like zorin os/zorin os lite guide to be availible (i use zorin os lite ofc)

**Comment by electron271alt** [comment]
@theandor

**Comment by electron271alt** [comment]
ehh later illl just make one

**Comment by theandor** [comment]
This would be a useless guide because Zorin Os is based on **Ubuntu Linux** which in turn is based on **Debian Linux** which has a guide.
